
spring:
  flyway:
    locations: classpath:db/migration
    enabled: true
  cloud:
    compatibility-verifier:
      enabled: false

datasource:
    equipment:
      pool-name: equipment
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/client_data_db
      username: postgres
      password: 123321

#server:
#  error:
#    include-stacktrace: never
#    include-message: always

#server:
#  error:
#    include-message: always
#    include-binding-errors: always
#    include-exception: false
#    include-stacktrace: never


